# Site settings
title: Book Club
email: contact@vansintjan.net
description: > # this means to ignore newlines until "baseurl:"
  An asynchronous book club
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simonv3.github.io/bookclub" # the base hostname & protocol for your site
twitter_username: false
github_username:  false

# Build settings
markdown: kramdown
